# Generated by Django 5.1.7 on 2025-03-29 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Длительность матча в секундах')),
                ('radiant_win', models.BooleanField()),
                ('radiant_team', models.CharField(blank=True, max_length=255, null=True)),
                ('dire_team', models.CharField(blank=True, max_length=255, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
