# Generated by Django 5.1.7 on 2025-03-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='patch',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
