# Generated by Django 5.1.7 on 2025-03-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_patch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='patch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
