# Generated by Django 5.1.7 on 2025-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_match_dire_team_remove_match_radiant_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dire_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='radiant_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
