# Generated by Django 5.1.7 on 2025-03-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_dire_team_id_alter_match_radiant_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='dire_team_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='radiant_team_id',
        ),
    ]
