# Generated by Django 5.1.7 on 2025-03-30 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(help_text='ID команды из OpenDota API', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('last_match_time', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='leagues.league')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['-rating'],
            },
        ),
    ]
