# Generated by Django 5.1.7 on 2025-03-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
    ]
