# Generated by Django 5.1.7 on 2025-03-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID героя')),
                ('name', models.CharField(help_text='Имя героя для API (например: "npc_dota_hero_antimage")', max_length=50, verbose_name='Техническое название')),
                ('localized_name', models.CharField(help_text='Имя героя для отображения (например: "Anti-Mage")', max_length=50, verbose_name='Локализованное имя')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герои',
                'ordering': ['localized_name'],
            },
        ),
    ]
