# Generated by Django 5.1.7 on 2025-03-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Команда')),
                ('team', models.CharField(max_length=50, verbose_name='Команда игрока')),
            ],
            options={
                'verbose_name': 'Команда',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ник игрока')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.team', verbose_name='Команда игрока')),
            ],
            options={
                'verbose_name': 'Игрок',
                'ordering': ['team', 'name'],
            },
        ),
    ]
