# Generated by Django 5.1.7 on 2025-03-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0007_match_dire_team_match_radiant_team'),
        ('teams', '0002_remove_team_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=50, verbose_name='ID героя')),
                ('is_pick', models.BooleanField(help_text='True - пик, False - бан', verbose_name='Тип действия')),
                ('order', models.IntegerField(verbose_name='Порядковый номер действия')),
                ('stage', models.CharField(choices=[('ban_1-7', 'Первый этап банов(1-7)'), ('first_pick', 'Первый пик'), ('second_pick', 'Второй пик'), ('ban_10-12', 'Второй этап банов(10-12)'), ('pick_13-18', 'Второй этап пиков(13-18)'), ('ban_19-22', 'Третий этап банов(19-22)'), ('pick_23', '23 пик'), ('pick_24', 'Ластпик')], max_length=20, verbose_name='Стадия драфта')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_timings', to='matches.match', verbose_name='Матч')),
                ('team', models.ForeignKey(blank=True, help_text='Команда, совершившая действие', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Действие драфта',
                'verbose_name_plural': 'Тайминг драфта',
                'ordering': ['match', 'order'],
                'unique_together': {('match', 'order')},
            },
        ),
    ]
