# Generated by Django 5.1.7 on 2025-03-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_timings', '0001_initial'),
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafttiming',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.hero', verbose_name='Герой'),
        ),
    ]
